server:
  port: 9000
  servlet:
    context-path: /auth
spring:
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name:com.mysql.cj.jdbc.Driver}
    url: jdbc:mysql://localhost:3306/ordersystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username:root}
    password: ${sky.datasource.password:123456}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/auth
logging:
  level:
    com.sia.grserver: debug